import { Employee } from './employee.model';

export const employees: Employee[] = [
  {
    id: 1,
    name: 'Darya',
    surname: 'Kokorina',
    patronymic: 'Vladimirovna',
    salary: 100,
    room: 301,
    hours: 20,
    email: 'darya.kakoryna@marshmallow.com',
  },
  {
    id: 2,
    name: 'Diana',
    surname: 'Kashrina',
    patronymic: 'Vladimirovna',
    salary: 200,
    room: 302,
    hours: 26,
    email: 'diana.kashrina@marshmallow.com',
  },
  {
    id: 3,
    name: 'Dmirty',
    surname: 'Barodzich',
    patronymic: 'Vitalievich',
    salary: 50,
    room: 303,
    hours: 40,
    email: 'dmitry.barodzich@marshmallow.com',
  },
  {
    id: 4,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 5,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 6,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 7,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 8,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 9,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 10,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 11,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 12,
    name: 'Maskim',
    surname: 'Smel\'',
    patronymic: 'Dmitrievich',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'maksim.smel@marshmallow.com',
  },
  {
    id: 13,
    name: 'Alice',
    surname: 'Smel\'',
    patronymic: 'Dmitrievna',
    salary: 500,
    room: 304,
    hours: 50,
    email: 'alice.smel@marshmallow.com',
  },
];

export const newEmployee = {
  name: 'Vanyusha',
  surname: 'Smel\'',
  patronymic: 'Dmitrievich',
  salary: 500,
  room: 304,
  hours: 50,
  email: 'vanyusha.smel@marshmallow.com',
};
